# gcloud builds submit . --substitutions _REGION=us-central1,_REPO_NAME=consumer-edge --project fto-cloud-build-project-231a

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/generate-isos', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/generate-isos']

images: ['${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/generate-isos']
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/gcb-generate-iso@$PROJECT_ID.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY